// src/generators/html-generator.ts
import * as fs from 'fs';
import * as path from 'path';
import { Project, Table, Column, Mapping } from '../types/ast';

export class HTMLGenerator {
  generate(ast: Project, outputDir: string): void {
    // Create output directory
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Generate index page
    this.generateIndexPage(ast, outputDir);

    // Generate table pages
    for (const target of ast.targets) {
      for (const table of target.tables) {
        this.generateTablePage(ast, target, table, outputDir);
      }
    }

    // Generate lineage page
    this.generateLineagePage(ast, outputDir);

    // Generate mapping matrix page
    this.generateMappingMatrixPage(ast, outputDir);

    console.log(`✓ Generated documentation in ${outputDir}`);
  }

  private generateIndexPage(ast: Project, outputDir: string): void {
    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${ast.project} - Database Documentation</title>
  <style>
    ${this.getBaseStyles()}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>📊 ${ast.project}</h1>
      <p class="subtitle">${ast.description || 'Database Documentation'}</p>
      ${ast.owners && ast.owners.length > 0 ? `
        <p class="owners">👥 Owners: ${ast.owners.join(', ')}</p>
      ` : ''}
    </header>

    <nav class="nav">
      <a href="index.html" class="active">Home</a>
      <a href="lineage.html">Lineage</a>
      <a href="mapping-matrix.html">Mapping Matrix</a>

    </nav>

    <section>
      <h2>Target Databases</h2>
      ${ast.targets.map(target => `
        <div class="card">
          <h3>🗄️ ${target.db}</h3>
          <p><strong>Engine:</strong> ${target.engine}</p>
          ${target.schema ? `<p><strong>Schema:</strong> ${target.schema}</p>` : ''}
          <h4>Tables (${target.tables.length})</h4>
          <ul>
            ${target.tables.map(table => `
              <li>
                <a href="${this.getTableFileName(target.db, table.name)}">
                  ${table.name}
                </a>
                ${table.description ? `<span class="desc">- ${table.description}</span>` : ''}
              </li>
            `).join('')}
          </ul>
        </div>
      `).join('')}
    </section>

    <section>
      <h2>Source Systems</h2>
      ${ast.sources.map(source => `
        <div class="card">
          <h3>📥 ${source.id}</h3>
          <p><strong>Type:</strong> ${source.kind}</p>
          ${source.db ? `<p><strong>Database:</strong> ${source.db}</p>` : ''}
          ${source.collection ? `<p><strong>Collection:</strong> ${source.collection}</p>` : ''}
          ${source.description ? `<p>${source.description}</p>` : ''}
        </div>
      `).join('')}
    </section>

    <footer>
      <p>Generated by DBDocManager v${ast.version || '1.0.0'} on ${new Date().toLocaleDateString()}</p>
    </footer>
  </div>
</body>
</html>
    `;

    fs.writeFileSync(path.join(outputDir, 'index.html'), html);
  }

  private generateMappingMatrixPage(ast: Project, outputDir: string): void {
    const rows = ast.mappings.map(m => `
    <tr>
      <td><code>${m.target}</code></td>
      <td><span class="badge-source">${m.from.source_id}</span></td>
      <td><code>${m.from.path || '-'}</code></td>
      <td>${m.from.transform ? `<span class="badge-transform">${m.from.transform}</span>` : '-'}</td>
      <td>${m.description || '-'}</td>
    </tr>
  `).join('');

    const mappingData = JSON.stringify(ast.mappings, null, 2);

    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Mapping Matrix - ${ast.project}</title>
  <style>
  :root {
    --primary: #3498db;
    --primary-dark: #217dbb;
    --bg-light: #f4f6f9;
    --card-bg: #ffffff;
    --border: #e1e5eb;
    --text-dark: #2c3e50;
    --text-medium: #5f6c7b;
  }

  * {
    margin: 0; padding: 0;
    box-sizing: border-box;
    font-family: "Inter", system-ui, sans-serif;
  }

  body {
    background: var(--bg-light);
    color: var(--text-dark);
  }

  .container {
    max-width: 1300px;
    margin: auto;
    padding: 25px;
    background: white;
    border-radius: 10px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.08);
  }

  header h1 {
    font-size: 2.4rem;
    font-weight: 700;
    color: var(--text-dark);
    display: flex;
    align-items: center;
    gap: 12px;
  }

  .subtitle {
    color: var(--text-medium);
    margin-top: 6px;
    font-size: 1.1rem;
  }

  .nav {
    display: flex;
    gap: 20px;
    margin: 22px 0;
    border-bottom: 1px solid var(--border);
    padding-bottom: 10px;
  }
  .nav a {
    color: var(--primary);
    text-decoration: none;
    font-weight: 500;
    padding: 6px 12px;
    border-radius: 6px;
  }
  .nav a.active {
    background: var(--primary);
    color: white;
  }

  .controls {
    display: flex;
    justify-content: space-between;
    margin-bottom: 15px;
  }

  #searchBox {
    padding: 10px;
    width: 250px;
    border: 1px solid var(--border);
    border-radius: 6px;
    font-size: 0.95rem;
  }

  .download-btn {
    background: var(--primary);
    color: white;
    border: none;
    border-radius: 6px;
    padding: 10px 16px;
    cursor: pointer;
    font-weight: 600;
  }
  .download-btn:hover { background: var(--primary-dark); }

  /* TABLE */
  table {
    width: 100%;
    border-collapse: collapse;
    background: white;
    border-radius: 10px;
    overflow: hidden;
    margin-top: 10px;
    box-shadow: 0 2px 6px rgba(0,0,0,0.08);
  }

  thead th {
    background: var(--primary);
    color: white;
    padding: 14px;
    font-size: 0.95rem;
    text-align: left;
    position: sticky;
    top: 0;
    z-index: 2;
    cursor: pointer;
  }

  tbody tr:nth-child(even) { background: #f9fbfd; }
  tbody tr:hover { background: #eef5ff; }

  td {
    padding: 14px;
    font-size: 0.92rem;
    border-bottom: 1px solid var(--border);
  }

  /* Badges */
  .badge-transform {
    background: #ecf5ff;
    color: #1673c4;
    padding: 3px 7px;
    border-radius: 6px;
    font-size: 0.8rem;
    font-weight: 600;
  }

  .badge-source {
    background: #fff4e5;
    padding: 3px 7px;
    border-radius: 6px;
    color: #b06a00;
    font-size: 0.8rem;
    font-weight: 600;
  }

  code {
    background: #f0f3f7;
    padding: 3px 6px;
    border-radius: 4px;
  }
  </style>
</head>
<body>
<div class="container">
  <header>
    <h1>📊 Mapping Matrix</h1>
    <p class="subtitle">Complete view of all column-level mappings</p>
  </header>

  <nav class="nav">
    <a href="index.html">Home</a>
    <a href="lineage.html">Lineage</a>
    <a href="mapping-matrix.html" class="active">Mapping Matrix</a>
  </nav>

  <div class="controls">
    <input type="text" id="searchBox" placeholder="Search...">
    <button class="download-btn" onclick="downloadCSV()">⬇ Download CSV</button>
  </div>

  <table id="matrixTable">
    <thead>
      <tr>
        <th>Target</th>
        <th>Source</th>
        <th>Path</th>
        <th>Transform</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      ${rows}
    </tbody>
  </table>
</div>

<script>
const MAPPINGS = ${mappingData};

document.getElementById("searchBox").addEventListener("input", function () {
  const value = this.value.toLowerCase();
  document.querySelectorAll("#matrixTable tbody tr").forEach(row => {
    row.style.display = row.innerText.toLowerCase().includes(value) ? "" : "none";
  });
});

// SORTING
document.querySelectorAll("th").forEach((th, index) => {
  th.addEventListener("click", () => sortTable(index));
});

function sortTable(colIndex) {
  const table = document.getElementById("matrixTable");
  const rows = Array.from(table.rows).slice(1);
  let sorted = rows.sort((a, b) =>
    a.cells[colIndex].innerText.localeCompare(b.cells[colIndex].innerText)
  );
  sorted.forEach(row => table.tBodies[0].appendChild(row));
}

// CSV DOWNLOAD - generate from AST mappings (clean values, proper escaping)
function downloadCSV() {
  let csv = "Target,Source,Path,Transform,Description\\n";

  MAPPINGS.forEach(m => {
    const row = [
      m.target,
      m.from.source_id,
      m.from.path || "-",
      m.from.transform || "-",
      m.description || "-"
    ].map(v => '"' + String(v).replace(/"/g, '""') + '"').join(',');

    csv += row + "\\n";
  });

  const blob = new Blob([csv], { type: "text/csv" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = "mapping-matrix.csv";
  a.click();
}
</script>

</body>
</html>
`;

    fs.writeFileSync(path.join(outputDir, 'mapping-matrix.html'), html);
  }

  private generateTablePage(ast: Project, target: any, table: Table, outputDir: string): void {
    const mappings = this.getTableMappings(ast, target, table);

    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${table.name} - ${ast.project}</title>
  <style>
    ${this.getBaseStyles()}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>📋 ${table.name}</h1>
      <p class="breadcrumb">
        <a href="index.html">${ast.project}</a> / 
        ${target.db} / 
        ${table.name}
      </p>
    </header>

    <nav class="nav">
      <a href="index.html">Home</a>
      <a href="lineage.html">Lineage</a>
      <a href="mapping-matrix.html">Mapping Matrix</a>
    </nav>

    ${table.description ? `
      <section>
        <p class="table-description">${table.description}</p>
      </section>
    ` : ''}

    <section>
      <h2>Columns</h2>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Constraints</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          ${table.columns.map(col => `
            <tr>
              <td><strong>${col.name}</strong></td>
              <td><code>${col.type}</code></td>
              <td>
                ${col.pk ? '<span class="badge pk">PK</span>' : ''}
                ${col.unique ? '<span class="badge unique">UNIQUE</span>' : ''}
                ${col.auto_increment ? '<span class="badge auto">AUTO</span>' : ''}
                ${!col.nullable ? '<span class="badge not-null">NOT NULL</span>' : ''}
                ${col.default ? `<span class="badge default">DEFAULT: ${col.default}</span>` : ''}
              </td>
              <td>${col.description || '<em>No description</em>'}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </section>

    ${mappings.length > 0 ? `
      <section>
        <h2>Data Lineage</h2>
        <table>
          <thead>
            <tr>
              <th>Column</th>
              <th>Source</th>
              <th>Path</th>
              <th>Transform</th>
            </tr>
          </thead>
          <tbody>
            ${mappings.map(m => `
              <tr>
                <td><strong>${m.columnName}</strong></td>
                <td>${m.sourceId}</td>
                <td><code>${m.path}</code></td>
                <td>${m.transform ? `<code>${m.transform}</code>` : '-'}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </section>
    ` : ''}

    ${table.foreign_keys && table.foreign_keys.length > 0 ? `
      <section>
        <h2>Foreign Keys</h2>
        <ul>
          ${table.foreign_keys.map(fk => `
            <li>
              <strong>${fk.name}:</strong> 
              ${fk.columns.join(', ')} → ${fk.references.table}(${fk.references.columns.join(', ')})
              ${fk.on_delete ? `<span class="badge">${fk.on_delete}</span>` : ''}
            </li>
          `).join('')}
        </ul>
      </section>
    ` : ''}

    <footer>
      <p><a href="index.html">← Back to Home</a></p>
    </footer>
  </div>
</body>
</html>
    `;

    const fileName = this.getTableFileName(target.db, table.name);
    fs.writeFileSync(path.join(outputDir, fileName), html);
  }

  private generateLineagePage(ast: Project, outputDir: string): void {
    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Data Lineage - ${ast.project}</title>
  <style>
    ${this.getBaseStyles()}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>🔗 Data Lineage</h1>
      <p class="subtitle">Source → Target Mappings</p>
    </header>

    <nav class="nav">
      <a href="index.html">Home</a>
      <a href="lineage.html" class="active">Lineage</a>
      <a href="mapping-matrix.html">Mapping Matrix</a>

    </nav>

    <section>
      <h2>All Mappings (${ast.mappings.length})</h2>
      <table>
        <thead>
          <tr>
            <th>Target</th>
            <th>Source</th>
            <th>Path</th>
            <th>Transform</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          ${ast.mappings.map(m => `
            <tr>
              <td><code>${m.target}</code></td>
              <td><strong>${m.from.source_id}</strong></td>
              <td><code>${m.from.path}</code></td>
              <td>${m.from.transform ? `<code>${m.from.transform}</code>` : '-'}</td>
              <td>${m.description || '-'}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </section>

    <footer>
      <p><a href="index.html">← Back to Home</a></p>
    </footer>
  </div>
</body>
</html>
    `;

    fs.writeFileSync(path.join(outputDir, 'lineage.html'), html);
  }

  private getTableMappings(ast: Project, target: any, table: Table): any[] {
    const mappings = [];
    
    for (const mapping of ast.mappings) {
      const parts = mapping.target.split('.');
      const tableName = parts[parts.length - 2];
      const columnName = parts[parts.length - 1];

      if (tableName === table.name) {
        mappings.push({
          columnName,
          sourceId: mapping.from.source_id,
          path: mapping.from.path,
          transform: mapping.from.transform
        });
      }
    }

    return mappings;
  }

  private getTableFileName(db: string, table: string): string {
    return `table_${db}_${table}.html`;
  }

  private getBaseStyles(): string {
    return `
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        line-height: 1.6;
        color: #333;
        background: #f5f5f5;
      }
      .container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 20px;
        background: white;
        min-height: 100vh;
      }
      header {
        border-bottom: 3px solid #4CAF50;
        padding-bottom: 20px;
        margin-bottom: 30px;
      }
      h1 { color: #2c3e50; font-size: 2.5em; margin-bottom: 10px; }
      h2 { color: #34495e; margin: 30px 0 15px; font-size: 1.8em; }
      h3 { color: #555; margin: 15px 0 10px; }
      .subtitle { color: #7f8c8d; font-size: 1.2em; }
      .breadcrumb { color: #95a5a6; margin-top: 10px; }
      .breadcrumb a { color: #3498db; text-decoration: none; }
      .breadcrumb a:hover { text-decoration: underline; }
      .owners { color: #7f8c8d; font-size: 0.95em; margin-top: 10px; }
      .nav {
        display: flex;
        gap: 20px;
        margin-bottom: 30px;
        border-bottom: 2px solid #ecf0f1;
        padding-bottom: 10px;
      }
      .nav a {
        text-decoration: none;
        color: #3498db;
        padding: 5px 10px;
        border-radius: 4px;
      }
      .nav a:hover { background: #ecf0f1; }
      .nav a.active { background: #3498db; color: white; }
      section { margin: 30px 0; }
      .card {
        background: #fafafa;
        border: 1px solid #e0e0e0;
        border-radius: 8px;
        padding: 20px;
        margin-bottom: 20px;
      }
      table {
        width: 100%;
        border-collapse: collapse;
        margin: 15px 0;
        background: white;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      }
      th, td {
        padding: 12px;
        text-align: left;
        border-bottom: 1px solid #e0e0e0;
      }
      th {
        background: #34495e;
        color: white;
        font-weight: 600;
      }
      tr:hover { background: #f8f9fa; }
      code {
        background: #ecf0f1;
        padding: 2px 6px;
        border-radius: 3px;
        font-family: 'Courier New', monospace;
        font-size: 0.9em;
      }
      .badge {
        display: inline-block;
        padding: 3px 8px;
        border-radius: 4px;
        font-size: 0.75em;
        font-weight: bold;
        margin-right: 5px;
      }
      .badge.pk { background: #e74c3c; color: white; }
      .badge.unique { background: #f39c12; color: white; }
      .badge.auto { background: #9b59b6; color: white; }
      .badge.not-null { background: #3498db; color: white; }
      .badge.default { background: #95a5a6; color: white; }
      ul { padding-left: 20px; }
      li { margin: 8px 0; }
      .desc { color: #7f8c8d; font-size: 0.9em; }
      .table-description {
        background: #e8f5e9;
        padding: 15px;
        border-left: 4px solid #4CAF50;
        margin-bottom: 20px;
      }
      footer {
        margin-top: 50px;
        padding-top: 20px;
        border-top: 1px solid #e0e0e0;
        color: #95a5a6;
        text-align: center;
      }
      footer a { color: #3498db; text-decoration: none; }
      footer a:hover { text-decoration: underline; }
    `;
  }
}