// src/generators/html-generator.ts
import * as fs from 'fs';
import * as path from 'path';
import { Project, Table, Column, Mapping, Source } from '../types/ast';
export class HTMLGenerator {
  generate(ast: Project, outputDir: string): void {
    // Create output directory
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Generate index page
    this.generateIndexPage(ast, outputDir);

    // Generate table pages
    for (const target of ast.targets) {
      for (const table of target.tables) {
        this.generateTablePage(ast, target, table, outputDir);
      }
    }

    // Generate lineage page
    this.generateLineagePage(ast, outputDir);
// Generate data and graph page for lineage
    this.generateLineageGraphData(ast, outputDir);
    this.generateLineageGraphPage(ast, outputDir);
    console.log(`✓ Generated documentation in ${outputDir}`);
  }

  private generateIndexPage(ast: Project, outputDir: string): void {
    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${ast.project} - Database Documentation</title>
  <style>
    ${this.getBaseStyles()}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>📊 ${ast.project}</h1>
      <p class="subtitle">${ast.description || 'Database Documentation'}</p>
      ${ast.owners && ast.owners.length > 0 ? `
        <p class="owners">👥 Owners: ${ast.owners.join(', ')}</p>
      ` : ''}
    </header>

    <nav class="nav">
      <a href="index.html" class="active">Home</a>
      <a href="lineage.html">Lineage</a>
      <a href="lineage-graph.html">Lineage (Graph)</a>
    </nav>

    <section>
      <h2>Target Databases</h2>
      ${ast.targets.map(target => `
        <div class="card">
          <h3>🗄️ ${target.db}</h3>
          <p><strong>Engine:</strong> ${target.engine}</p>
          ${target.schema ? `<p><strong>Schema:</strong> ${target.schema}</p>` : ''}
          <h4>Tables (${target.tables.length})</h4>
          <ul>
            ${target.tables.map(table => `
              <li>
                <a href="${this.getTableFileName(target.db, table.name)}">
                  ${table.name}
                </a>
                ${table.description ? `<span class="desc">- ${table.description}</span>` : ''}
              </li>
            `).join('')}
          </ul>
        </div>
      `).join('')}
    </section>

    <section>
      <h2>Source Systems</h2>
      ${ast.sources.map(source => `
        <div class="card">
          <h3>📥 ${source.id}</h3>
          <p><strong>Type:</strong> ${source.kind}</p>
          ${source.db ? `<p><strong>Database:</strong> ${source.db}</p>` : ''}
          ${source.collection ? `<p><strong>Collection:</strong> ${source.collection}</p>` : ''}
          ${source.description ? `<p>${source.description}</p>` : ''}
        </div>
      `).join('')}
    </section>

    <footer>
      <p>Generated by DBDocManager v${ast.version || '1.0.0'} on ${new Date().toLocaleDateString()}</p>
    </footer>
  </div>
</body>
</html>
    `;

    fs.writeFileSync(path.join(outputDir, 'index.html'), html);
  }

  private generateTablePage(ast: Project, target: any, table: Table, outputDir: string): void {
    const mappings = this.getTableMappings(ast, target, table);

    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${table.name} - ${ast.project}</title>
  <style>
    ${this.getBaseStyles()}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>📋 ${table.name}</h1>
      <p class="breadcrumb">
        <a href="index.html">${ast.project}</a> / 
        ${target.db} / 
        ${table.name}
      </p>
    </header>

    <nav class="nav">
      <a href="index.html">Home</a>
      <a href="lineage.html">Lineage</a>
      <a href="lineage-graph.html">Lineage (Graph)</a>
    </nav>

    ${table.description ? `
      <section>
        <p class="table-description">${table.description}</p>
      </section>
    ` : ''}

    <section>
      <h2>Columns</h2>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Constraints</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          ${table.columns.map(col => `
            <tr>
              <td><strong>${col.name}</strong></td>
              <td><code>${col.type}</code></td>
              <td>
                ${col.pk ? '<span class="badge pk">PK</span>' : ''}
                ${col.unique ? '<span class="badge unique">UNIQUE</span>' : ''}
                ${col.auto_increment ? '<span class="badge auto">AUTO</span>' : ''}
                ${!col.nullable ? '<span class="badge not-null">NOT NULL</span>' : ''}
                ${col.default ? `<span class="badge default">DEFAULT: ${col.default}</span>` : ''}
              </td>
              <td>${col.description || '<em>No description</em>'}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </section>

    ${mappings.length > 0 ? `
      <section>
        <h2>Data Lineage</h2>
        <table>
          <thead>
            <tr>
              <th>Column</th>
              <th>Source</th>
              <th>Path</th>
              <th>Transform</th>
            </tr>
          </thead>
          <tbody>
            ${mappings.map(m => `
              <tr>
                <td><strong>${m.columnName}</strong></td>
                <td>${m.sourceId}</td>
                <td><code>${m.path}</code></td>
                <td>${m.transform ? `<code>${m.transform}</code>` : '-'}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </section>
    ` : ''}

    ${table.foreign_keys && table.foreign_keys.length > 0 ? `
      <section>
        <h2>Foreign Keys</h2>
        <ul>
          ${table.foreign_keys.map(fk => `
            <li>
              <strong>${fk.name}:</strong> 
              ${fk.columns.join(', ')} → ${fk.references.table}(${fk.references.columns.join(', ')})
              ${fk.on_delete ? `<span class="badge">${fk.on_delete}</span>` : ''}
            </li>
          `).join('')}
        </ul>
      </section>
    ` : ''}

    <footer>
      <p><a href="index.html">← Back to Home</a></p>
    </footer>
  </div>
</body>
</html>
    `;

    const fileName = this.getTableFileName(target.db, table.name);
    fs.writeFileSync(path.join(outputDir, fileName), html);
  }

  private generateLineagePage(ast: Project, outputDir: string): void {
    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Data Lineage - ${ast.project}</title>
  <style>
    ${this.getBaseStyles()}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>🔗 Data Lineage</h1>
      <p class="subtitle">Source → Target Mappings</p>
    </header>

    <nav class="nav">
      <a href="index.html">Home</a>
      <a href="lineage.html" class="active">Lineage</a>
      <a href="lineage-graph.html">Lineage (Graph)</a>
    </nav>

    <section>
      <h2>All Mappings (${ast.mappings.length})</h2>
      <table>
        <thead>
          <tr>
            <th>Target</th>
            <th>Source</th>
            <th>Path</th>
            <th>Transform</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          ${ast.mappings.map(m => `
            <tr>
              <td><code>${m.target}</code></td>
              <td><strong>${m.from.source_id}</strong></td>
              <td><code>${m.from.path}</code></td>
              <td>${m.from.transform ? `<code>${m.from.transform}</code>` : '-'}</td>
              <td>${m.description || '-'}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </section>

    <footer>
      <p><a href="index.html">← Back to Home</a></p>
    </footer>
  </div>
</body>
</html>
    `;

    fs.writeFileSync(path.join(outputDir, 'lineage.html'), html);
  }

  private getTableMappings(ast: Project, target: any, table: Table): any[] {
    const mappings = [];
    
    for (const mapping of ast.mappings) {
      const parts = mapping.target.split('.');
      const tableName = parts[parts.length - 2];
      const columnName = parts[parts.length - 1];

      if (tableName === table.name) {
        mappings.push({
          columnName,
          sourceId: mapping.from.source_id,
          path: mapping.from.path,
          transform: mapping.from.transform
        });
      }
    }

    return mappings;
  }

  private getTableFileName(db: string, table: string): string {
    return `table_${db}_${table}.html`;
  }

  private getBaseStyles(): string {
    return `
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        line-height: 1.6;
        color: #333;
        background: #f5f5f5;
      }
      .container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 20px;
        background: white;
        min-height: 100vh;
      }
      header {
        border-bottom: 3px solid #4CAF50;
        padding-bottom: 20px;
        margin-bottom: 30px;
      }
      h1 { color: #2c3e50; font-size: 2.5em; margin-bottom: 10px; }
      h2 { color: #34495e; margin: 30px 0 15px; font-size: 1.8em; }
      h3 { color: #555; margin: 15px 0 10px; }
      .subtitle { color: #7f8c8d; font-size: 1.2em; }
      .breadcrumb { color: #95a5a6; margin-top: 10px; }
      .breadcrumb a { color: #3498db; text-decoration: none; }
      .breadcrumb a:hover { text-decoration: underline; }
      .owners { color: #7f8c8d; font-size: 0.95em; margin-top: 10px; }
      .nav {
        display: flex;
        gap: 20px;
        margin-bottom: 30px;
        border-bottom: 2px solid #ecf0f1;
        padding-bottom: 10px;
      }
      .nav a {
        text-decoration: none;
        color: #3498db;
        padding: 5px 10px;
        border-radius: 4px;
      }
      .nav a:hover { background: #ecf0f1; }
      .nav a.active { background: #3498db; color: white; }
      section { margin: 30px 0; }
      .card {
        background: #fafafa;
        border: 1px solid #e0e0e0;
        border-radius: 8px;
        padding: 20px;
        margin-bottom: 20px;
      }
      table {
        width: 100%;
        border-collapse: collapse;
        margin: 15px 0;
        background: white;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      }
      th, td {
        padding: 12px;
        text-align: left;
        border-bottom: 1px solid #e0e0e0;
      }
      th {
        background: #34495e;
        color: white;
        font-weight: 600;
      }
      tr:hover { background: #f8f9fa; }
      code {
        background: #ecf0f1;
        padding: 2px 6px;
        border-radius: 3px;
        font-family: 'Courier New', monospace;
        font-size: 0.9em;
      }
      .badge {
        display: inline-block;
        padding: 3px 8px;
        border-radius: 4px;
        font-size: 0.75em;
        font-weight: bold;
        margin-right: 5px;
      }
      .badge.pk { background: #e74c3c; color: white; }
      .badge.unique { background: #f39c12; color: white; }
      .badge.auto { background: #9b59b6; color: white; }
      .badge.not-null { background: #3498db; color: white; }
      .badge.default { background: #95a5a6; color: white; }
      ul { padding-left: 20px; }
      li { margin: 8px 0; }
      .desc { color: #7f8c8d; font-size: 0.9em; }
      .table-description {
        background: #e8f5e9;
        padding: 15px;
        border-left: 4px solid #4CAF50;
        margin-bottom: 20px;
      }
      footer {
        margin-top: 50px;
        padding-top: 20px;
        border-top: 1px solid #e0e0e0;
        color: #95a5a6;
        text-align: center;
      }
      footer a { color: #3498db; text-decoration: none; }
      footer a:hover { text-decoration: underline; }
    `;
  }
 // backend for generating lineage graph data with transforms
  private generateLineageGraphData(ast: Project, outputDir: string): void {
    console.log('Generating column-level lineage graph data with transforms...');

    // Define the data structure for graph elements
    interface GraphElementData {
      id: string;
      label: string;
      type: 'source-parent' | 'target-parent' | 'source-column' | 'target-column';
      kind?: string;
      parent?: string;
    }

    interface GraphElement {
      data: GraphElementData;
    }

    interface GraphEdge {
      data: {
        id: string;
        source: string; // ID of the source *column*
        target: string; // ID of the target *column*
        label?: string; // <-- NEW: For transform labels
      };
    }

    const nodes = new Map<string, GraphElement>();
    const edges = new Map<string, GraphEdge>();

    const sourceMap = new Map<string, Source>(
      ast.sources.map((s) => [s.id, s])
    );

    for (const mapping of ast.mappings) {
      try {
        const targetFQN = mapping.target;
        const targetParts = targetFQN.split('.');
        if (targetParts.length < 4) continue;

        const targetTableId = targetParts.slice(0, 3).join('.');
        const targetTableLabel = targetParts[2];
        const targetColumnId = targetFQN;
        const targetColumnLabel = targetParts[3];

        const sourceId = mapping.from.source_id;
        const sourcePath = mapping.from.path;
        const sourceColumnId = `${sourceId}:${sourcePath}`;

        const sourceObj = sourceMap.get(sourceId);
        if (!sourceObj) continue;

        const sourceTableLabel = sourceObj.collection || sourceObj.id;
        const sourceColumnLabel = sourcePath;
        const sourceKind = sourceObj.kind;

        if (!nodes.has(targetTableId)) {
          nodes.set(targetTableId, {
            data: {
              id: targetTableId,
              label: targetTableLabel,
              type: 'target-parent',
            },
          });
        }
        if (!nodes.has(sourceId)) {
          nodes.set(sourceId, {
            data: {
              id: sourceId,
              label: sourceTableLabel,
              type: 'source-parent',
              kind: sourceKind,
            },
          });
        }

        if (!nodes.has(targetColumnId)) {
          nodes.set(targetColumnId, {
            data: {
              id: targetColumnId,
              label: targetColumnLabel,
              type: 'target-column',
              parent: targetTableId,
            },
          });
        }
        if (!nodes.has(sourceColumnId)) {
          nodes.set(sourceColumnId, {
            data: {
              id: sourceColumnId,
              label: sourceColumnLabel,
              type: 'source-column',
              parent: sourceId,
            },
          });
        }

        const edgeId = `${sourceColumnId}_to_${targetColumnId}`;
        if (!edges.has(edgeId)) {
          edges.set(edgeId, {
            data: {
              id: edgeId,
              source: sourceColumnId,
              target: targetColumnId,
              label: mapping.from.transform, // <-- NEW: Add the transform string as a label
            },
          });
        }
      } catch (e) {
        console.error(`Error processing mapping for ${mapping.target}:`, e);
      }
    }

    const graphData = {
      nodes: Array.from(nodes.values()),
      edges: Array.from(edges.values()),
    };

    const outputPath = path.join(outputDir, 'lineage-data.json');
    fs.writeFileSync(outputPath, JSON.stringify(graphData, null, 2));

    console.log(`✓ Generated column-level lineage data at ${outputPath}`);
  }
  // fronntend for the lineage graph
  private generateLineageGraphPage(ast: Project, outputDir: string): void {
    const html = `
<!DOCTYPE html>
<html>
<head>
  <title>Lineage Graph - ${ast.project}</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.23.0/cytoscape.min.js"></script>
  <script src="https://unpkg.com/dagre@0.8.5/dist/dagre.min.js"></script>
  <script src="https://unpkg.com/cytoscape-dagre@2.5.0/cytoscape-dagre.js"></script>
<style>
    ${this.getBaseStyles()}
    #cy {
      width: 100%;
      height: 80vh;
      border: 1px solid #e0e0e0;
      background: #fafafa;
      box-sizing: border-box;
    }
    .cytoscape-tooltip {
        background: #333;
        color: white;
        padding: 5px 10px;
        border-radius: 4px;
        position: absolute;
        z-index: 1000;
        pointer-events: none;
        font-size: 12px;
        white-space: nowrap;
        opacity: 0;
        transition: opacity 0.2s ease-in-out;
    }
    .cytoscape-tooltip.active {
        opacity: 1;
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>🧬 Data Lineage Graph</h1>
      <p class="subtitle">Visualizing Column-Level Source → Target dependencies</p>
    </header>

    <nav class="nav">
      <a href="index.html">Home</a>
      <a href="lineage.html">Lineage (Table)</a>
      <a href="lineage-graph.html" class="active">Lineage (Graph)</a>
    </nav>

    <section>
      <div id="cy"></div>
    </section>

    <footer>
      <p><a href="index.html">← Back to Home</a></p>
    </footer>
  </div>

  <script>
    cytoscape.use(cytoscapeDagre);

    document.addEventListener('DOMContentLoaded', function () {
      fetch('./lineage-data.json')
        .then((res) => res.json())
        .then((data) => {
          var cy = cytoscape({
            container: document.getElementById('cy'),
            elements: data,
            style: [
              {
                selector: 'edge',
                style: {
                  'curve-style': 'bezier',
                  'target-arrow-shape': 'triangle',
                  'line-color': '#7f8c8d',
                  'target-arrow-color': '#7f8c8d',
                  'width': 1,
                },
              },
              // --- NEW STYLE FOR TRANSFORM LABELS ---
              {
                selector: 'edge[label]', // Only applies to edges that *have* a label
                style: {
                  'label': 'data(label)',
                  'font-size': '9px',
                  'color': '#0B5345', // Dark green/blue
                  'font-weight': 'bold',
                  'text-background-opacity': 1,
                  'text-background-color': '#F8F9F9', // Light background
                  'text-background-padding': '2px',
                  'text-background-shape': 'round-rectangle',
                  'edge-text-rotation': 'autorotate',
                  'text-margin-y': -10, // Move label slightly off the line
                }
              },
              // --- END NEW STYLE ---
              {
                selector: 'node',
                style: {
                  'shape': 'round-rectangle',
                  'border-width': '1px',
                  'border-color': '#555',
                  'label': 'data(label)',
                  'text-valign': 'center',
                  'text-halign': 'center',
                  'font-family': 'Arial, sans-serif',
                  'text-wrap': 'wrap',
                  'text-max-width': '80px',
                  'font-size': '10px',
                  'background-color': '#fdfefe',
                }
              },
              {
                selector: ':parent',
                style: {
                  'background-opacity': 0.15,
                  'border-style': 'solid',
                  'font-size': '14px',
                  'font-weight': 'bold',
                  'text-valign': 'top',
                  'text-halign': 'center',
                  'padding': '20px',
                  'label': 'data(label)',
                  'text-margin-y': '-5px',
                },
              },
              {
                selector: 'node[type="source-parent"]',
                style: {
                  'background-color': '#EBF5FB',
                  'border-color': '#5DADE2',
                  'text-outline-color': '#EBF5FB',
                  'text-outline-width': 2,
                },
              },
              {
                selector: 'node[type="target-parent"]',
                style: {
                  'background-color': '#FEF9E7',
                  'border-color': '#F7DC6F',
                  'text-outline-color': '#FEF9E7',
                  'text-outline-width': 2,
                },
              },
              {
                selector: 'node[type="source-column"]',
                style: {
                  'background-color': '#AED6F1',
                  'border-color': '#5DADE2',
                  'font-size': '10px',
                  'width': '110px',
                  'height': '30px',
                },
              },
              {
                selector: 'node[type="target-column"]',
                style: {
                  'background-color': '#FAD7A0',
                  'border-color': '#F7DC6F',
                  'font-size': '10px',
                  'width': '110px',
                  'height': '30px',
                },
              },
              {
                selector: '.highlighted',
                style: {
                  'background-color': '#5cb85c',
                  'line-color': '#5cb85c',
                  'target-arrow-color': '#5cb85c',
                  'transition-property': 'background-color, line-color, target-arrow-color',
                  'transition-duration': '0.3s'
                }
              }
            ],
            
            // --- UPDATED LAYOUT SETTINGS ---
            layout: {
              name: 'dagre',
              rankDir: 'LR',
              spacingFactor: 1.3, // A bit more overall spacing
              nodeSep: 30, // Tighter vertical spacing for columns
              edgeSep: 10,
              rankSep: 150, // More horizontal spacing between tables
              padding: 40,
              fit: true,
              animate: false,
              nodeDimensionsIncludeLabels: true,
            },
            // --- END UPDATED LAYOUT ---
          });

          // (The tooltip script remains the same)
          cy.on('mouseover', 'node[type$="-column"]', function(event) {
              const node = event.target;
              const tooltip = document.createElement('div');
              tooltip.className = 'cytoscape-tooltip';
              tooltip.textContent = node.data('id');
              document.body.appendChild(tooltip);

              const updateTooltipPos = (e) => {
                  tooltip.style.left = (e.pageX + 10) + 'px';
                  tooltip.style.top = (e.pageY + 10) + 'px';
              };
              updateTooltipPos(event.originalEvent);
              tooltip.classList.add('active');

              cy.on('mousemove', updateTooltipPos);

              node.on('mouseout', function() {
                  tooltip.classList.remove('active');
                  tooltip.remove();
                  cy.off('mousemove', updateTooltipPos);
              });
          });

        })
        .catch((e) => {
          console.error('Error fetching lineage data:', e);
          document.getElementById('cy').innerHTML = '<strong>Error loading lineage data.</strong><br>Did you run the generator? Is lineage-data.json available?';
        });
    });
  </script>
</body>
</html>
    `;
    fs.writeFileSync(path.join(outputDir, 'lineage-graph.html'), html);
  }

}