import * as fs from 'fs';
import * as path from 'path';
import { Project, Table, Column, Mapping, Source } from '../types/ast';
import { ERGenerator } from './er-generator';

export class HTMLGenerator {
  generate(ast: Project, outputDir: string): void {
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Generate pages
    this.generateIndexPage(ast, outputDir);
    
    for (const target of ast.targets) {
      for (const table of target.tables) {
        this.generateTablePage(ast, target, table, outputDir);
      }
    }

    this.generateLineagePage(ast, outputDir);
    this.generateLineageGraphData(ast, outputDir); // Backend data
    this.generateLineageGraphPage(ast, outputDir); // Frontend graph
    this.generateERDAssets(ast, outputDir);

    console.log(`✓ Generated Interactive Lineage Graph in ${outputDir}`);
  }

  // --- 1. SHARED LAYOUT HELPERS ---

  private getPageLayout(ast: Project, title: string, content: string, activeLink: string): string {
    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <!-- Scripts for Graph -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.23.0/cytoscape.min.js"></script>
  <script src="https://unpkg.com/dagre@0.8.5/dist/dagre.min.js"></script>
  <script src="https://unpkg.com/cytoscape-dagre@2.5.0/cytoscape-dagre.js"></script>
  <style>
    ${this.getClaritySidebarStyles()}
  </style>
</head>
<body>
  <div class="app-layout">
    <!-- SIDEBAR -->
    <aside class="sidebar">
      <div class="brand">
        <div class="logo-icon">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></svg>
        </div>
        <div class="brand-text">${ast.project}</div>
      </div>
      
      <nav class="side-nav">
        <div class="nav-section">
          <span class="nav-header">Overview</span>
          <a href="index.html" class="nav-item ${activeLink === 'home' ? 'active' : ''}">
             <span class="icon">🏠</span> Dashboard
          </a>
          <a href="erd.html" class="nav-item ${activeLink === 'erd' ? 'active' : ''}">
              <span class="icon">📐</span> ER Diagram
          </a>
          <a href="lineage.html" class="nav-item ${activeLink === 'lineage-table' ? 'active' : ''}">
             <span class="icon">🔢</span> Lineage Matrix
          </a>
          <a href="lineage-graph.html" class="nav-item ${activeLink === 'lineage-graph' ? 'active' : ''}">
             <span class="icon">🕸️</span> Visual Graph
          </a>
        </div>

        <div class="nav-section">
          <span class="nav-header">Target Tables</span>
          ${ast.targets.map(t => 
            t.tables.map(table => `
              <a href="${this.getTableFileName(t.db, table.name)}" 
                 class="nav-item ${activeLink === table.name ? 'active' : ''}">
                 <span class="icon">📄</span> ${table.name}
              </a>
            `).join('')
          ).join('')}
        </div>

        <div class="nav-section">
          <span class="nav-header">Source Systems</span>
          ${ast.sources.map(s => `
            <div class="nav-item static">
               <span class="icon">📥</span> ${s.id}
            </div>
          `).join('')}
        </div>
      </nav>

      <div class="sidebar-footer">
        <span class="version-badge">v${ast.version || '1.0'}</span>
      </div>
    </aside>

    <!-- MAIN CONTENT -->
    <main class="main-content">
      <!-- Subtle Background Blob -->
      <div class="bg-gradient-blob"></div>
      
      <div class="content-wrapper">
        ${content}
      </div>

      <footer class="page-footer">
        Generated by DBDocManager
      </footer>
    </main>
  </div>
</body>
</html>
    `;
  }

  // --- 2. PAGE GENERATORS ---

  private generateIndexPage(ast: Project, outputDir: string): void {
    const content = `
      <header class="page-header">
        <div>
          <h1>Dashboard</h1>
          <p class="subtitle">${ast.description || 'Project Overview'}</p>
        </div>
        ${ast.owners ? `<div class="meta-badge">👥 Owners: ${ast.owners.join(', ')}</div>` : ''}
      </header>

      <div class="stats-grid">
        <div class="stat-card">
          <div class="stat-icon purple">🗄</div>
          <div>
            <div class="stat-value">${ast.targets.reduce((acc, t) => acc + t.tables.length, 0)}</div>
            <div class="stat-label">Tables Defined</div>
          </div>
        </div>
        <div class="stat-card">
          <div class="stat-icon blue">📥</div>
          <div>
            <div class="stat-value">${ast.sources.length}</div>
            <div class="stat-label">Source Systems</div>
          </div>
        </div>
        <div class="stat-card">
          <div class="stat-icon pink">🔗</div>
          <div>
            <div class="stat-value">${ast.mappings.length}</div>
            <div class="stat-label">Field Mappings</div>
          </div>
        </div>
      </div>

      <div class="section-title">Databases & Schemas</div>
      <div class="card-grid">
        ${ast.targets.map(target => `
          <div class="card">
            <div class="card-header">
              <h3>🗄️ ${target.db}</h3>
              <span class="badge bg-purple">${target.engine}</span>
            </div>
            <div class="card-body">
              ${target.schema ? `<p class="meta-row"><strong>Schema:</strong> ${target.schema}</p>` : ''}
              <ul class="table-list">
                ${target.tables.map(table => `
                  <li>
                    <a href="${this.getTableFileName(target.db, table.name)}">
                      ${table.name}
                    </a>
                  </li>
                `).join('')}
              </ul>
            </div>
          </div>
        `).join('')}
      </div>

      <div class="section-title" style="margin-top: 2rem;">Source Systems</div>
      <div class="card-grid">
        ${ast.sources.map(source => `
          <div class="card">
             <div class="card-header">
              <h3>📥 ${source.id}</h3>
              <span class="badge outline">${source.kind}</span>
            </div>
            <div class="card-body">
              <div class="meta-grid">
                ${source.db ? `<div><span class="label">DB</span> ${source.db}</div>` : ''}
                ${source.collection ? `<div><span class="label">COLL</span> ${source.collection}</div>` : ''}
              </div>
              <p class="text-muted mt-2">${source.description || 'No description provided.'}</p>
            </div>
          </div>
        `).join('')}
      </div>
    `;

    fs.writeFileSync(path.join(outputDir, 'index.html'), this.getPageLayout(ast, 'Dashboard', content, 'home'));
  }

  private generateTablePage(ast: Project, target: any, table: Table, outputDir: string): void {
    const mappings = this.getTableMappings(ast, target, table);
    const content = `
      <header class="page-header">
        <div>
          <div class="breadcrumbs">${target.db} / ${target.schema || 'public'} /</div>
          <h1>${table.name}</h1>
        </div>
        <span class="badge bg-purple-light">${table.columns.length} Columns</span>
      </header>

      ${table.description ? `
        <div class="callout">
          ${table.description}
        </div>
      ` : ''}

      <div class="card">
        <div class="card-title">Schema Definition</div>
        <div class="table-responsive">
          <table class="data-table">
            <thead>
              <tr>
                <th width="30%">Column</th>
                <th width="15%">Type</th>
                <th width="15%">Attributes</th>
                <th>Description</th>
              </tr>
            </thead>
            <tbody>
              ${table.columns.map(col => `
                <tr>
                  <td class="font-mono font-bold text-dark">${col.name}</td>
                  <td class="font-mono text-purple">${col.type}</td>
                  <td>
                    ${col.pk ? '<span class="badge pk">PK</span>' : ''}
                    ${col.unique ? '<span class="badge unique">UQ</span>' : ''}
                    ${!col.nullable ? '<span class="badge nn">NN</span>' : ''}
                    ${col.default ? `<span class="badge def" title="Default: ${col.default}">DEF</span>` : ''}
                  </td>
                  <td class="text-muted">${col.description || '-'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>
      </div>

      ${mappings.length > 0 ? `
        <div class="card" style="margin-top: 2rem;">
          <div class="card-title">Lineage & Mappings</div>
          <div class="table-responsive">
            <table class="data-table">
              <thead>
                <tr>
                  <th>Target Column</th>
                  <th>Source System</th>
                  <th>Source Path</th>
                  <th>Transform</th>
                </tr>
              </thead>
              <tbody>
                ${mappings.map(m => `
                  <tr>
                    <td class="font-mono font-bold">${m.columnName}</td>
                    <td><span class="badge source">${m.sourceId}</span></td>
                    <td class="font-mono text-muted">${m.path}</td>
                    <td>${m.transform ? `<code class="code-pill">${m.transform}</code>` : '<span class="text-muted">-</span>'}</td>
                  </tr>
                `).join('')}
              </tbody>
            </table>
          </div>
        </div>
      ` : ''}
    `;

    const fileName = this.getTableFileName(target.db, table.name);
    fs.writeFileSync(path.join(outputDir, fileName), this.getPageLayout(ast, table.name, content, table.name));
  }

  private generateLineagePage(ast: Project, outputDir: string): void {
    const content = `
      <header class="page-header">
        <div>
           <h1>Data Lineage Matrix</h1>
           <p class="subtitle">Full listing of Source → Target mappings</p>
        </div>
      </header>

      <div class="card">
        <div class="table-responsive">
          <table class="data-table">
            <thead>
              <tr>
                <th>Target Column</th>
                <th>Source</th>
                <th>Source Path</th>
                <th>Transformation</th>
                <th>Notes</th>
              </tr>
            </thead>
            <tbody>
              ${ast.mappings.map(m => `
                <tr>
                  <td class="font-mono font-medium">${m.target}</td>
                  <td><strong class="text-dark">${m.from.source_id}</strong></td>
                  <td class="font-mono text-purple">${m.from.path}</td>
                  <td>${m.from.transform ? `<code class="code-pill">${m.from.transform}</code>` : '-'}</td>
                  <td class="text-sm text-muted">${m.description || '-'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>
      </div>
    `;
    fs.writeFileSync(path.join(outputDir, 'lineage.html'), this.getPageLayout(ast, 'Lineage', content, 'lineage-table'));
  }

  private generateLineageGraphPage(ast: Project, outputDir: string): void {
    const content = `
      <header class="page-header">
        <div>
           <h1>Data Lineage Graph</h1>
           <p class="subtitle">Interactive Column-Level Dependencies</p>
        </div>
        <div class="legend">
           <span class="legend-item"><span class="dot blue"></span> Source</span>
           <span class="legend-item"><span class="dot yellow"></span> Target</span>
        </div>
      </header>

      <div class="card" style="height: 75vh; padding: 0; overflow: hidden; border-radius: 12px; position: relative;">
        <!-- The Graph Container -->
        <div id="cy" style="width: 100%; height: 100%;"></div>
        
        <!-- Floating Controls -->
        <div class="controls">
            <button id="zoom-in" class="control-btn" title="Zoom In">+</button>
            <button id="zoom-out" class="control-btn" title="Zoom Out">−</button>
            <div class="divider"></div>
            <button id="fit-view" class="control-btn" title="Reset View">⟲</button>
        </div>
      </div>

      <script>
        cytoscape.use(cytoscapeDagre);
        document.addEventListener('DOMContentLoaded', function () {
          fetch('./lineage-data.json')
            .then((res) => res.json())
            .then((data) => {
              var cy = cytoscape({
                container: document.getElementById('cy'),
                elements: data,
                minZoom: 0.1,
                maxZoom: 3,
                wheelSensitivity: 0.2, // Smoother wheel zoom
                style: [
                  {
                    selector: 'node',
                    style: {
                      'shape': 'round-rectangle',
                      'border-width': '1px',
                      'border-color': '#e2e8f0',
                      'label': 'data(label)',
                      'text-valign': 'center',
                      'text-halign': 'center',
                      'font-family': 'Inter, sans-serif',
                      'font-size': '11px',
                      'color': '#334155',
                      'background-color': '#ffffff',
                      'width': '120px',
                      'height': '34px',
                      'text-wrap': 'ellipsis',
                      'text-max-width': '110px',
                      'shadow-blur': '4px',
                      'shadow-color': 'rgba(0,0,0,0.05)',
                      'shadow-opacity': 1
                    }
                  },
                  {
                    selector: ':parent',
                    style: {
                      'background-color': '#f8fafc',
                      'background-opacity': 0.5,
                      'border-width': '1px',
                      'border-color': '#cbd5e1',
                      'border-style': 'dashed',
                      'label': 'data(label)',
                      'text-valign': 'top',
                      'text-halign': 'center',
                      'font-size': '12px',
                      'font-weight': 'bold',
                      'color': '#64748b',
                      'padding': '25px',
                      'text-margin-y': '-8px'
                    },
                  },
                  {
                    selector: 'edge',
                    style: {
                      'curve-style': 'bezier',
                      'width': 1.5,
                      'line-color': '#94a3b8',
                      'target-arrow-color': '#94a3b8',
                      'target-arrow-shape': 'triangle'
                    }
                  },
                  {
                    selector: 'edge[label]',
                    style: {
                      'label': 'data(label)',
                      'font-size': '9px',
                      'color': '#7c3aed',
                      'text-background-color': '#ffffff',
                      'text-background-opacity': 1,
                      'text-background-padding': '3px',
                      'text-background-shape': 'round-rectangle',
                      'text-border-width': '1px',
                      'text-border-color': '#f3e8ff',
                      'edge-text-rotation': 'autorotate'
                    }
                  },
                  {
                    selector: 'node[type="source-column"]',
                    style: { 'border-left-width': '3px', 'border-left-color': '#60a5fa' }
                  },
                  {
                    selector: 'node[type="target-column"]',
                    style: { 'border-left-width': '3px', 'border-left-color': '#fbbf24' }
                  },
                  // Grab state styles
                  {
                    selector: 'core',
                    style: {
                      'active-bg-opacity': 0
                    }
                  }
                ],
                layout: {
                  name: 'dagre',
                  rankDir: 'LR',
                  spacingFactor: 1.2,
                  nodeSep: 40,
                  rankSep: 150,
                  padding: 50,
                  nodeDimensionsIncludeLabels: true
                }
              });

              // --- CONTROLS LOGIC ---
              
              // Zoom In
              document.getElementById('zoom-in').addEventListener('click', function() {
                cy.animate({
                  zoom: {
                    level: cy.zoom() * 1.2,
                    position: { x: cy.width() / 2, y: cy.height() / 2 }
                  },
                  duration: 300
                });
              });

              // Zoom Out
              document.getElementById('zoom-out').addEventListener('click', function() {
                cy.animate({
                  zoom: {
                    level: cy.zoom() * 0.8,
                    position: { x: cy.width() / 2, y: cy.height() / 2 }
                  },
                  duration: 300
                });
              });

              // Reset (Fit)
              document.getElementById('fit-view').addEventListener('click', function() {
                cy.animate({
                  fit: { padding: 50 },
                  duration: 500
                });
              });

            });
        });
      </script>
    `;
    fs.writeFileSync(path.join(outputDir, 'lineage-graph.html'), this.getPageLayout(ast, 'Graph', content, 'lineage-graph'));
  }

  // --- 3. BACKEND DATA GENERATOR (Unchanged) ---
  private generateLineageGraphData(ast: Project, outputDir: string): void {
    interface GraphElement { data: any; }
    const nodes = new Map<string, GraphElement>();
    const edges = new Map<string, any>();
    const sourceMap = new Map<string, Source>(ast.sources.map((s) => [s.id, s]));

    for (const mapping of ast.mappings) {
      try {
        const targetParts = mapping.target.split('.');
        if (targetParts.length < 4) continue;

        const targetTableId = targetParts.slice(0, 3).join('.');
        const targetTableLabel = targetParts[2];
        const targetColumnId = mapping.target;
        const targetColumnLabel = targetParts[3];

        const sourceId = mapping.from.source_id;
        const sourcePath = mapping.from.path;
        const sourceColumnId = `${sourceId}:${sourcePath}`;
        const sourceObj = sourceMap.get(sourceId);
        
        if (!sourceObj) continue;

        if (!nodes.has(targetTableId)) {
          nodes.set(targetTableId, { data: { id: targetTableId, label: targetTableLabel, type: 'target-parent' }});
        }
        if (!nodes.has(sourceId)) {
          nodes.set(sourceId, { data: { id: sourceId, label: sourceObj.collection || sourceId, type: 'source-parent', kind: sourceObj.kind }});
        }
        if (!nodes.has(targetColumnId)) {
          nodes.set(targetColumnId, { data: { id: targetColumnId, label: targetColumnLabel, type: 'target-column', parent: targetTableId }});
        }
        if (!nodes.has(sourceColumnId)) {
          nodes.set(sourceColumnId, { data: { id: sourceColumnId, label: sourcePath, type: 'source-column', parent: sourceId }});
        }

        const edgeId = `${sourceColumnId}_to_${targetColumnId}`;
        if (!edges.has(edgeId)) {
            edges.set(edgeId, { data: { id: edgeId, source: sourceColumnId, target: targetColumnId, label: mapping.from.transform }});
        }
      } catch(e) {}
    }

    const graphData = { nodes: Array.from(nodes.values()), edges: Array.from(edges.values()) };
    fs.writeFileSync(path.join(outputDir, 'lineage-data.json'), JSON.stringify(graphData, null, 2));
  }

  // --- 4. CLARITY SIDEBAR CSS (Enhanced for Graph Controls) ---
  private getClaritySidebarStyles(): string {
    return `
      /* CLARITY THEME - VARIABLES */
      :root {
        --sidebar-width: 260px;
        --primary: #1e293b;
        --accent: #7c3aed; /* Purple 600 */
        --accent-light: #f5f3ff; /* Purple 50 */
        --text-dark: #0f172a;
        --text-muted: #64748b;
        --bg-body: #ffffff;
        --bg-sidebar: #f8fafc;
        --border: #e2e8f0;
        --font-sans: 'Inter', system-ui, -apple-system, sans-serif;
        --font-mono: 'JetBrains Mono', monospace;
      }

      /* RESET */
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body {
        font-family: var(--font-sans);
        color: var(--text-dark);
        background-color: var(--bg-body);
        line-height: 1.6;
        min-height: 100vh;
        display: flex;
      }

      /* LAYOUT */
      .app-layout {
        display: flex;
        width: 100%;
        min-height: 100vh;
      }

      /* SIDEBAR STYLES */
      .sidebar {
        width: var(--sidebar-width);
        background-color: var(--bg-sidebar);
        border-right: 1px solid var(--border);
        height: 100vh;
        position: fixed;
        left: 0;
        top: 0;
        overflow-y: auto;
        display: flex;
        flex-direction: column;
        z-index: 50;
      }

      .brand {
        padding: 1.5rem;
        display: flex;
        align-items: center;
        gap: 0.75rem;
        border-bottom: 1px solid var(--border);
      }
      .logo-icon {
        width: 32px; height: 32px; 
        background: linear-gradient(135deg, #7c3aed, #3b82f6); 
        border-radius: 8px; 
        display: flex; align-items: center; justify-content: center; 
        color: white;
      }
      .brand-text { font-weight: 700; font-size: 1.1rem; color: var(--text-dark); }

      .side-nav { padding: 1.5rem 1rem; flex: 1; }
      .nav-section { margin-bottom: 2rem; }
      .nav-header {
        text-transform: uppercase; font-size: 0.7rem; font-weight: 700;
        color: #94a3b8; margin-bottom: 0.5rem; padding-left: 0.75rem; letter-spacing: 0.05em;
      }

      .nav-item {
        display: flex; align-items: center; gap: 0.75rem; padding: 0.6rem 0.75rem;
        color: var(--text-muted); text-decoration: none; border-radius: 8px;
        font-size: 0.9rem; font-weight: 500; margin-bottom: 0.25rem; transition: all 0.2s;
      }
      .nav-item:hover { background-color: white; color: var(--accent); box-shadow: 0 1px 2px rgba(0,0,0,0.05); }
      .nav-item.active { background-color: var(--accent-light); color: var(--accent); font-weight: 600; }
      .nav-item.static { cursor: default; opacity: 0.8; }

      .sidebar-footer { padding: 1.5rem; border-top: 1px solid var(--border); text-align: center; }
      .version-badge { background: #e2e8f0; color: #475569; padding: 0.2rem 0.6rem; border-radius: 99px; font-size: 0.75rem; font-weight: 600; }

      /* MAIN CONTENT */
      .main-content { margin-left: var(--sidebar-width); flex: 1; padding: 3rem; width: calc(100% - var(--sidebar-width)); }
      .content-wrapper { max-width: 1200px; margin: 0 auto; }
      .bg-gradient-blob { position: fixed; top: -20%; right: -10%; width: 600px; height: 600px; background: radial-gradient(circle at center, rgba(232, 218, 255, 0.4) 0%, rgba(255, 255, 255, 0) 70%); z-index: -1; pointer-events: none; }

      /* COMPONENTS */
      .page-header { margin-bottom: 2.5rem; display: flex; justify-content: space-between; align-items: start; }
      h1 { font-size: 2rem; font-weight: 700; color: var(--text-dark); margin: 0.5rem 0 0 0; letter-spacing: -0.5px; }
      .subtitle { color: var(--text-muted); font-size: 1.1rem; margin-top: 0.25rem; }
      .breadcrumbs { font-size: 0.8rem; color: #94a3b8; font-weight: 600; text-transform: uppercase; }
      
      .card { background: white; border-radius: 12px; border: 1px solid var(--border); box-shadow: 0 2px 4px rgba(0,0,0,0.02); margin-bottom: 1.5rem; overflow: hidden; }
      .card-header { padding: 1.25rem 1.5rem; border-bottom: 1px solid var(--border); display: flex; justify-content: space-between; align-items: center; background: #fcfcfc; }
      .card-header h3 { margin: 0; font-size: 1rem; font-weight: 600; color: var(--text-dark); }
      .card-body { padding: 1.5rem; }
      .card-title { padding: 1rem 1.5rem; border-bottom: 1px solid var(--border); font-weight: 600; color: var(--text-dark); background: #fcfcfc; }

      .stats-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem; margin-bottom: 3rem; }
      .stat-card { background: white; border: 1px solid var(--border); border-radius: 12px; padding: 1.5rem; display: flex; align-items: center; gap: 1rem; box-shadow: 0 2px 5px rgba(0,0,0,0.02); }
      .stat-icon { width: 48px; height: 48px; border-radius: 10px; display: flex; align-items: center; justify-content: center; font-size: 1.5rem; }
      .stat-icon.purple { background: #f3e8ff; }
      .stat-icon.blue { background: #e0f2fe; }
      .stat-icon.pink { background: #fce7f3; }
      .stat-value { font-size: 1.5rem; font-weight: 700; color: var(--text-dark); line-height: 1; }
      .stat-label { font-size: 0.85rem; color: var(--text-muted); font-weight: 500; margin-top: 0.25rem; }
      
      .card-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(350px, 1fr)); gap: 1.5rem; }
      
      /* TABLES */
      .table-responsive { overflow-x: auto; }
      .data-table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
      .data-table th { text-align: left; padding: 0.85rem 1.25rem; background: #f8fafc; color: var(--text-muted); font-weight: 600; font-size: 0.75rem; text-transform: uppercase; border-bottom: 1px solid var(--border); }
      .data-table td { padding: 1rem 1.25rem; border-bottom: 1px solid var(--border); color: var(--text-dark); vertical-align: top; }
      .data-table tr:last-child td { border-bottom: none; }

      /* BADGES */
      .badge { display: inline-block; padding: 0.2rem 0.5rem; border-radius: 6px; font-size: 0.7rem; font-weight: 700; text-transform: uppercase; }
      .badge.bg-purple { background: #eff6ff; color: var(--accent); }
      .badge.bg-purple-light { background: var(--accent-light); color: var(--accent); }
      .badge.outline { border: 1px solid var(--accent); color: var(--accent); }
      .badge.pk { background: #fee2e2; color: #dc2626; }
      .badge.unique { background: #ffedd5; color: #ea580c; }
      .badge.nn { background: #e0f2fe; color: #0284c7; }
      .badge.def { background: #f1f5f9; color: #64748b; }
      .badge.source { background: #dcfce7; color: #166534; font-family: var(--font-mono); text-transform: none; font-size: 0.8rem; }
      .code-pill { background: #f1f5f9; padding: 0.15rem 0.4rem; border-radius: 4px; font-family: var(--font-mono); font-size: 0.85em; color: #475569; border: 1px solid #e2e8f0; }

      ul.table-list { list-style: none; padding: 0; margin: 0; }
      ul.table-list li { border-bottom: 1px solid #f1f5f9; }
      ul.table-list a { display: block; padding: 0.75rem 0; color: var(--text-dark); text-decoration: none; font-weight: 500; font-size: 0.95rem; transition: color 0.2s; }
      ul.table-list a:hover { color: var(--accent); }
      
      .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin-top: 0.5rem; font-size: 0.85rem; color: var(--text-muted); }
      .meta-grid .label { font-weight: 700; color: var(--text-dark); font-size: 0.7rem; margin-right: 0.25rem; background: #f1f5f9; padding: 0.1rem 0.3rem; rounded: 3px; }
      .meta-badge { display: inline-block; margin-top: 0.5rem; font-size: 0.85rem; color: var(--text-muted); background: white; padding: 0.25rem 0.75rem; border-radius: 20px; border: 1px solid var(--border); }
      
      .legend { display: flex; gap: 1rem; align-items: center; }
      .legend-item { display: flex; align-items: center; gap: 0.5rem; font-size: 0.85rem; color: var(--text-muted); }
      .dot { width: 8px; height: 8px; border-radius: 50%; }
      .dot.blue { background: #60a5fa; }
      .dot.yellow { background: #fbbf24; }

      /* GRAPH CONTROLS */
      #cy { cursor: grab; }
      #cy:active { cursor: grabbing; }
      
      .controls {
        position: absolute;
        bottom: 20px;
        right: 20px;
        display: flex;
        flex-direction: column;
        gap: 8px;
        z-index: 10;
        background: white;
        padding: 8px;
        border-radius: 10px;
        box-shadow: 0 4px 12px rgba(0,0,0,0.1);
        border: 1px solid var(--border);
      }
      .control-btn {
        width: 36px;
        height: 36px;
        background: white;
        border: 1px solid transparent;
        border-radius: 8px;
        display: flex;
        align-items: center;
        justify-content: center;
        cursor: pointer;
        color: var(--text-muted);
        font-size: 1.2rem;
        font-weight: 600;
        transition: all 0.2s;
      }
      .control-btn:hover {
        color: var(--accent);
        background-color: var(--accent-light);
      }
      .divider { height: 1px; background: var(--border); margin: 2px 0; }

      .page-footer { margin-top: 4rem; text-align: center; color: #94a3b8; font-size: 0.85rem; padding-bottom: 2rem; }
      .font-mono { font-family: var(--font-mono); }
      .text-purple { color: var(--accent); }
      .text-muted { color: #64748b; }
      .text-dark { color: var(--text-dark); }
    `;
  }

  // --- 5. UTILITIES ---
  private getTableMappings(ast: Project, target: any, table: Table): any[] {
    const mappings = [];
    for (const mapping of ast.mappings) {
      const parts = mapping.target.split('.');
      const tableName = parts[parts.length - 2];
      const columnName = parts[parts.length - 1];
      if (tableName === table.name) {
        mappings.push({ columnName, sourceId: mapping.from.source_id, path: mapping.from.path, transform: mapping.from.transform });
      }
    }
    return mappings;
  }

  private getTableFileName(db: string, table: string): string {
    return `table_${db}_${table}.html`;
  }
  
  private generateERDAssets(ast: Project, outputDir: string): void {
    // 1. Generate the Mermaid string from the AST
    const erGen = new ERGenerator();
    const mermaidCode = erGen.generateMermaidCode(ast);
    
    // 2. Save the physical file (as a backup/download option)
    fs.writeFileSync(path.join(outputDir, 'schema.mmd'), mermaidCode);

    // 3. The HTML Content
    const content = `
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.4.1/backbone-min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jointjs/3.7.5/joint.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dagre/0.8.5/dagre.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/graphlib/2.1.8/graphlib.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jointjs/3.7.5/joint.min.css" />

    <style>
        /* SCALED DOWN BODY STYLES TO FIT CONTAINER */
        #er-wrapper * {
            box-sizing: border-box;
        }
        
        #er-wrapper { 
            margin: 0; 
            padding: 0;
            overflow: hidden; 
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; 
            background: #f6f8fa;
            width: 100%;
            height: 85vh; /* Adjusted to fit dashboard */
            position: relative;
            border-radius: 8px;
            border: 1px solid #e1e4e8;
        }
        
        #toolbar {
            position: absolute; /* Changed from fixed to absolute for dashboard containment */
            top: 20px; 
            left: 20px; 
            z-index: 1000;
            background: white; 
            padding: 12px 16px; 
            border-radius: 8px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15); 
            border: 1px solid #e1e4e8;
            display: flex; 
            gap: 12px; 
            align-items: center;
        }
        
        #toolbar button { 
            padding: 8px 16px; 
            cursor: pointer; 
            background: #fff; 
            border: 1px solid #d1d5da; 
            border-radius: 6px; 
            font-weight: 600; 
            font-size: 13px; 
            color: #24292e;
            transition: all 0.2s;
            font-family: inherit;
        }
        
        #toolbar button:hover { 
            background: #f6f8fa; 
            border-color: #8c959f;
        }
        
        #toolbar button:active {
            transform: scale(0.98);
        }
        
        #toolbar .btn-primary { 
            background: #0969da; 
            color: white; 
            border: 1px solid #0969da; 
        }
        
        #toolbar .btn-primary:hover { 
            background: #0356b6;
            border-color: #0356b6; 
        }
        
        .file-upload { 
            position: relative; 
            overflow: hidden; 
            display: inline-block; 
        }
        
        .file-upload input[type=file] { 
            position: absolute; 
            left: 0; 
            top: 0; 
            opacity: 0; 
            width: 100%; 
            height: 100%; 
            cursor: pointer; 
        }

        #paper-container { 
            width: 100%; 
            height: 100%; 
            overflow: hidden; 
            cursor: grab; 
            background-color: #f6f8fa;
            position: relative;
        }
        
        #paper-container.grabbing { 
            cursor: grabbing; 
        }

        #paper {
            width: 100%;
            height: 100%;
        }

        /* Make link labels non-interactive */
        .joint-link-label {
            pointer-events: none !important;
        }

        .joint-link .label-rect {
            pointer-events: none !important;
        }
    </style>

    <div id="er-wrapper">
        <div id="toolbar">
            <div class="file-upload">
                <button class="btn-primary">📂 Load .mmd File</button>
                <input type="file" id="file-input" accept=".mmd,.txt">
            </div>
            <button id="btn-zoom-in">🔍 Zoom In</button>
            <button id="btn-zoom-out">🔎 Zoom Out</button>
            <button id="btn-fit">⊡ Fit to Screen</button>
            <button id="btn-reset">↻ Reset View</button>
             <a href="schema.mmd" download style="margin-left:10px; font-size:12px; color:#0969da; text-decoration:none;">Download .mmd</a>
        </div>

        <div id="paper-container">
            <div id="paper"></div>
        </div>
    </div>

    <script>
        // --- INJECTED DATA: This allows the diagram to load instantly without fetch errors ---
        const embeddedMermaid = ${JSON.stringify(mermaidCode)};

        const namespace = joint.shapes;
        const graph = new joint.dia.Graph({}, { cellNamespace: namespace });
        
        const paper = new joint.dia.Paper({
            el: document.getElementById('paper'),
            model: graph,
            width: 5000,
            height: 5000,
            gridSize: 1,
            drawGrid: false,
            background: { color: 'transparent' },
            cellViewNamespace: namespace,
            interactive: function(cellView) {
                if (cellView.model.isLink()) {
                    // Links are completely non-interactive
                    return false;
                }
                // Elements (tables) are draggable
                return true;
            },
            async: true,
            frozen: true,
            linkPinning: false,
            defaultLink: function() {
                return new joint.shapes.standard.Link();
            }
        });

        // Helper function to measure text width accurately
        function measureText(text, fontSize, fontWeight, fontFamily) {
            if (!text) return 0;
            const canvas = measureText.canvas || (measureText.canvas = document.createElement('canvas'));
            const context = canvas.getContext('2d');
            context.font = \`\${fontWeight} \${fontSize}px \${fontFamily}\`;
            return context.measureText(text).width;
        }

        // Define custom table shape
        joint.shapes.standard.Rectangle.define('app.ERTable', {
            attrs: {
                body: { 
                    fill: '#ffffff', 
                    stroke: '#e1e4e8', 
                    strokeWidth: 1,
                    rx: 6,
                    ry: 6
                }
            }
        });

        // Enhanced parser with better error handling
        function parseMermaid(text) {
            const entities = {};
            const relationships = [];
            // TS ESCAPE: split('\\n')
            const lines = text.split('\\n');
            let currentEntity = null;

            lines.forEach((line, lineNum) => {
                line = line.trim();
                
                if(!line || line.startsWith('%%') || line.startsWith('erDiagram')) {
                    return;
                }

                // Parse relationship - improved regex
                // TS ESCAPE: Double backslashes for regex string definition
                const relMatch = line.match(/^(\\w+)\\s+([\\|\\}o\\{][|\\-o\\{]{2,}[\\|\\}o\\{])\\s+(\\w+)\\s*:\\s*"?([^"]+)"?$/);
                if(relMatch) {
                    relationships.push({ 
                        from: relMatch[1], 
                        to: relMatch[3], 
                        card: relMatch[2], 
                        label: relMatch[4].trim()
                    });
                    return; 
                }

                // Parse entity start
                const entStart = line.match(/^(\\w+)\\s*\\{$/);
                if(entStart) {
                    currentEntity = entStart[1];
                    entities[currentEntity] = { name: currentEntity, attributes: [] };
                    return;
                }
                
                // Parse entity end
                if(line === '}') { 
                    currentEntity = null; 
                    return; 
                }

                // Parse attributes - handles multiple quoted strings
                if(currentEntity) {
                    const quotes = [];
                    let quoteMatch;
                    const quoteRegex = /"([^"]*)"/g;
                    while ((quoteMatch = quoteRegex.exec(line)) !== null) {
                        quotes.push(quoteMatch[1]);
                    }

                    const cleanLine = line.replace(/"[^"]*"/g, '').trim();
                    // TS ESCAPE: split(/\\s+/)
                    const parts = cleanLine.split(/\\s+/).filter(p => p);

                    if(parts.length >= 2) {
                        const type = parts[0];
                        const name = parts[1];
                        const constraint = quotes[0] || '';
                        const description = quotes[1] || '';

                        entities[currentEntity].attributes.push({ 
                            type: type, 
                            name: name, 
                            constraint: constraint,
                            description: description
                        });
                    }
                }
            });
            
            return { entities, relationships };
        }

        // Build graph with robust sizing
        function buildGraph(data) {
            graph.clear();
            const cells = [];
            const entityMap = {};

            Object.values(data.entities).forEach(ent => {
                // Measure actual text widths
                const headerTextWidth = measureText(ent.name, 16, '600', '-apple-system, BlinkMacSystemFont, Segoe UI, sans-serif');
                
                let maxNameWidth = Math.max(100, headerTextWidth);
                let maxTypeWidth = 60;
                let maxConstraintWidth = 0;
                let maxDescWidth = 0;
                let hasDescription = false;
                
                ent.attributes.forEach(attr => {
                    const nameWidth = measureText(attr.name, 13, '500', '-apple-system, BlinkMacSystemFont, Segoe UI, sans-serif');
                    const typeWidth = measureText(attr.type, 12, 'normal', 'Consolas, Monaco, monospace');
                    
                    let constraintWidth = 0;
                    if (attr.constraint) {
                        const badges = attr.constraint.split(',').map(s => s.trim()).filter(s => s);
                        badges.forEach(badge => {
                            constraintWidth += badge.length * 7 + 18;
                        });
                    }
                    
                    let descWidth = 0;
                    if (attr.description) {
                        hasDescription = true;
                        descWidth = measureText(attr.description, 11, 'normal', '-apple-system, BlinkMacSystemFont, Segoe UI, sans-serif');
                    }
                    
                    maxNameWidth = Math.max(maxNameWidth, nameWidth);
                    maxTypeWidth = Math.max(maxTypeWidth, typeWidth);
                    maxConstraintWidth = Math.max(maxConstraintWidth, constraintWidth);
                    maxDescWidth = Math.max(maxDescWidth, descWidth);
                });
                
                // Calculate column widths with padding
                const nameColWidth = Math.max(160, maxNameWidth + 40 + maxConstraintWidth + 20);
                const typeColWidth = Math.max(110, maxTypeWidth + 30);
                const descColWidth = hasDescription ? Math.max(180, Math.min(450, maxDescWidth + 40)) : 0;
                
                const totalWidth = nameColWidth + typeColWidth + descColWidth;
                
                const headerHeight = 45;
                const rowHeight = 38;
                const rowCount = Math.max(1, ent.attributes.length);
                const totalHeight = headerHeight + (rowCount * rowHeight);

                const el = new joint.shapes.app.ERTable();
                el.resize(totalWidth, totalHeight);
                el.position(0, 0);
                el.set('id', ent.name);

                const markup = [];
                const attrs = {};

                // Body rectangle with shadow
                markup.push({ tagName: 'rect', selector: 'body' });
                attrs.body = {
                    width: totalWidth,
                    height: totalHeight,
                    fill: '#ffffff',
                    stroke: '#d0d7de',
                    strokeWidth: 1.5,
                    rx: 8,
                    ry: 8,
                    filter: { name: 'dropShadow', args: { dx: 0, dy: 3, blur: 12, opacity: 0.15 } }
                };

                // Header background
                markup.push({ tagName: 'rect', selector: 'header' });
                attrs.header = {
                    width: totalWidth,
                    height: headerHeight,
                    fill: '#f6f8fa',
                    stroke: 'none',
                    rx: 8,
                    ry: 8
                };

                // Header clip to prevent overflow
                markup.push({ tagName: 'rect', selector: 'headerClip' });
                attrs.headerClip = {
                    width: totalWidth,
                    height: headerHeight - 1,
                    fill: '#f6f8fa',
                    stroke: 'none',
                    rx: 0,
                    ry: 0
                };

                // Header bottom border
                markup.push({ tagName: 'line', selector: 'headerBorder' });
                attrs.headerBorder = {
                    x1: 0,
                    y1: headerHeight,
                    x2: totalWidth,
                    y2: headerHeight,
                    stroke: '#d0d7de',
                    strokeWidth: 1.5
                };

                // Header text
                markup.push({ tagName: 'text', selector: 'headerText' });
                attrs.headerText = {
                    text: ent.name,
                    x: 16,
                    y: headerHeight / 2,
                    textAnchor: 'start',
                    textVerticalAnchor: 'middle',
                    fill: '#0969da',
                    fontSize: 16,
                    fontWeight: '700',
                    fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, sans-serif'
                };

                // Vertical line between name and type
                markup.push({ tagName: 'line', selector: 'vline1' });
                attrs.vline1 = {
                    x1: nameColWidth,
                    y1: headerHeight,
                    x2: nameColWidth,
                    y2: totalHeight,
                    stroke: '#d0d7de',
                    strokeWidth: 1
                };

                // Vertical line between type and description
                if(descColWidth > 0) {
                    markup.push({ tagName: 'line', selector: 'vline2' });
                    attrs.vline2 = {
                        x1: nameColWidth + typeColWidth,
                        y1: headerHeight,
                        x2: nameColWidth + typeColWidth,
                        y2: totalHeight,
                        stroke: '#d0d7de',
                        strokeWidth: 1
                    };
                }

                // Rows
                ent.attributes.forEach((attr, index) => {
                    const y = headerHeight + (index * rowHeight);
                    
                    // Horizontal line
                    if (index > 0) {
                        markup.push({ tagName: 'line', selector: \`hline\${index}\` });
                        attrs[\`hline\${index}\`] = {
                            x1: 0,
                            y1: y,
                            x2: totalWidth,
                            y2: y,
                            stroke: '#eaeef2',
                            strokeWidth: 1
                        };
                    }

                    // Constraint badges
                    if (attr.constraint) {
                        const badges = attr.constraint.split(',').map(s => s.trim()).filter(s => s);
                        
                        let badgeX = nameColWidth - 12;
                        badges.reverse().forEach((badge, bIndex) => {
                            const badgeWidth = badge.length * 7 + 12;
                            badgeX -= badgeWidth;
                            
                            let badgeColor = '#f0f0f0';
                            let textColor = '#666';
                            
                            if(badge.includes('PK')) {
                                badgeColor = '#ffd7d7';
                                textColor = '#d32f2f';
                            } else if(badge.includes('FK')) {
                                badgeColor = '#e3f2fd';
                                textColor = '#1565c0';
                            } else if(badge.includes('UK') || badge.includes('UNIQUE')) {
                                badgeColor = '#fff3e0';
                                textColor = '#ef6c00';
                            } else if(badge.includes('NOT NULL')) {
                                badgeColor = '#e8f5e9';
                                textColor = '#2e7d32';
                            }
                            
                            // Badge background
                            markup.push({ tagName: 'rect', selector: \`constraintBg\${index}_\${bIndex}\` });
                            attrs[\`constraintBg\${index}_\${bIndex}\`] = {
                                x: badgeX,
                                y: y + rowHeight / 2 - 9,
                                width: badgeWidth,
                                height: 18,
                                fill: badgeColor,
                                stroke: 'none',
                                rx: 3,
                                ry: 3
                            };
                            
                            // Badge text
                            markup.push({ tagName: 'text', selector: \`constraint\${index}_\${bIndex}\` });
                            attrs[\`constraint\${index}_\${bIndex}\`] = {
                                text: badge,
                                x: badgeX + badgeWidth / 2,
                                y: y + rowHeight / 2,
                                textAnchor: 'middle',
                                textVerticalAnchor: 'middle',
                                fill: textColor,
                                fontSize: 10,
                                fontWeight: '700',
                                fontFamily: 'Consolas, Monaco, monospace'
                            };
                            
                            badgeX -= 6;
                        });
                    }

                    // Attribute name
                    markup.push({ tagName: 'text', selector: \`name\${index}\` });
                    attrs[\`name\${index}\`] = {
                        text: attr.name,
                        x: 16,
                        y: y + rowHeight / 2,
                        textAnchor: 'start',
                        textVerticalAnchor: 'middle',
                        fill: '#24292f',
                        fontSize: 13,
                        fontWeight: '600',
                        fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, sans-serif'
                    };

                    // Type
                    markup.push({ tagName: 'text', selector: \`type\${index}\` });
                    attrs[\`type\${index}\`] = {
                        text: attr.type,
                        x: nameColWidth + 12,
                        y: y + rowHeight / 2,
                        textAnchor: 'start',
                        textVerticalAnchor: 'middle',
                        fill: '#57606a',
                        fontSize: 12,
                        fontFamily: 'Consolas, Monaco, monospace'
                    };

                    // Description
                    if(attr.description && descColWidth > 0) {
                        const maxDescChars = Math.floor((descColWidth - 30) / 6);
                        const descText = attr.description.length > maxDescChars 
                            ? attr.description.substring(0, maxDescChars - 3) + '...' 
                            : attr.description;
                        
                        markup.push({ tagName: 'text', selector: \`desc\${index}\` });
                        attrs[\`desc\${index}\`] = {
                            text: descText,
                            x: nameColWidth + typeColWidth + 12,
                            y: y + rowHeight / 2,
                            textAnchor: 'start',
                            textVerticalAnchor: 'middle',
                            fill: '#656d76',
                            fontSize: 11,
                            fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, sans-serif'
                        };
                    }
                });

                el.set('markup', markup);
                el.attr(attrs);

                cells.push(el);
                entityMap[ent.name] = el;
            });

            // Build links with fixed labels
            const linkColors = ['#8b5cf6', '#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#ec4899'];
            let colorIndex = 0;

            data.relationships.forEach(rel => {
                const source = entityMap[rel.from];
                const target = entityMap[rel.to];
                
                if(!source || !target) {
                    console.warn(\`Relationship references non-existent table: \${rel.from} -> \${rel.to}\`);
                    return;
                }

                const linkColor = linkColors[colorIndex % linkColors.length];
                colorIndex++;

                const link = new joint.shapes.standard.Link({
                    source: { id: source.id },
                    target: { id: target.id },
                    router: { 
                        name: 'manhattan', 
                        args: { 
                            step: 15,
                            padding: 20
                        } 
                    },
                    connector: { 
                        name: 'rounded', 
                        args: { 
                            radius: 12 
                        } 
                    },
                    attrs: {
                        line: { 
                            stroke: linkColor, 
                            strokeWidth: 2.5,
                            strokeDasharray: '0',
                            targetMarker: {
                                type: 'path',
                                d: 'M 10 -5 0 0 10 5 z',
                                fill: linkColor,
                                stroke: linkColor
                            }
                        }
                    }
                });

                // Add FIXED label
                if(rel.label) {
                    link.appendLabel({
                        attrs: {
                            text: { 
                                text: rel.label, 
                                fill: linkColor, 
                                fontSize: 12, 
                                fontWeight: '700',
                                fontFamily: '-apple-system, sans-serif',
                                pointerEvents: 'none'
                            },
                            rect: { 
                                fill: 'white', 
                                stroke: linkColor, 
                                strokeWidth: 2, 
                                rx: 6, 
                                ry: 6,
                                ref: 'text',
                                refWidth: '150%',
                                refHeight: '180%',
                                refX: '-25%',
                                refY: '-40%',
                                pointerEvents: 'none'
                            }
                        },
                        position: { 
                            distance: 0.5,
                            offset: 0
                        }
                    });

                    // Make label completely non-movable
                    link.label(0, {
                        position: {
                            distance: 0.5,
                            offset: 0
                        }
                    });
                }
                
                cells.push(link);
            });

            graph.resetCells(cells);
            layoutGraph();
        }

        // Layout with dagre
        function layoutGraph() {
            const g = new dagre.graphlib.Graph();
            g.setGraph({ 
                rankdir: 'LR',
                nodesep: 100,
                ranksep: 180,
                marginx: 80, 
                marginy: 80,
                edgesep: 30
            });
            g.setDefaultEdgeLabel(() => ({}));

            graph.getElements().forEach(el => {
                g.setNode(el.id, { 
                    width: el.size().width, 
                    height: el.size().height 
                });
            });
            
            graph.getLinks().forEach(link => {
                const sourceId = link.source().id;
                const targetId = link.target().id;
                if (sourceId && targetId) {
                    g.setEdge(sourceId, targetId);
                }
            });

            dagre.layout(g);

            graph.getElements().forEach(el => {
                const node = g.node(el.id);
                if (node) {
                    el.position(node.x - node.width / 2, node.y - node.height / 2);
                }
            });
            
            paper.unfreeze();
            
            setTimeout(() => {
                fitToScreen();
            }, 100);
        }

        // Fit to screen function
        function fitToScreen() {
            try {
                paper.scaleContentToFit({ 
                    padding: 60, 
                    maxScale: 1.2,
                    minScale: 0.05,
                    useModelGeometry: true
                });
                scale = paper.scale().sx;
            } catch (e) {
                console.error('Error fitting to screen:', e);
            }
        }

        // Load default or from file
        function loadDefault() {
            try {
                // MODIFIED: Use the injected variable instead of fetch
                if (embeddedMermaid) {
                    paper.freeze();
                    const parsed = parseMermaid(embeddedMermaid);
                    buildGraph(parsed);
                } else {
                    // Fallback to sample
                    const sampleMMD = \`erDiagram
    dim_customers {
        INTEGER customer_id "PK, AUTO_INCREMENT" "Surrogate key for customer dimension"
        VARCHAR(255) email "UK, NOT NULL" "Primary email address normalized to lowercase"
        VARCHAR(200) full_name "NOT NULL" "Customer full name first and last"
        VARCHAR(500) address_street "" "Street address"
        VARCHAR(100) address_city "" "City"
        VARCHAR(20) postal_code "" "ZIP or Postal code"
    }
    fact_orders {
        INTEGER order_id "PK, AUTO_INCREMENT" "Unique order identifier"
        INTEGER customer_id "FK, NOT NULL" "Foreign key to dim_customers"
        TIMESTAMP order_date "NOT NULL" "Order placement date"
        DECIMAL(10,2) total_amount "NOT NULL" "Total order amount in USD"
        VARCHAR(50) status "NOT NULL" "Order status pending completed cancelled"
    }
    dim_customers ||--o{ fact_orders : "fk_orders_customer"\`;
            
                    paper.freeze();
                    const parsed = parseMermaid(sampleMMD);
                    buildGraph(parsed);
                }
            } catch (error) {
                console.log('Error loading diagram', error);
            }
        }

        // File upload handler
        document.getElementById('file-input').addEventListener('change', function(e) {
            const file = e.target.files[0];
            if(!file) return;
            
            const reader = new FileReader();
            reader.onload = (e) => {
                try {
                    paper.freeze();
                    const parsed = parseMermaid(e.target.result);
                    buildGraph(parsed);
                } catch (error) {
                    console.error('Error parsing file:', error);
                    alert('Error parsing .mmd file. Please check the format.');
                }
            };
            reader.onerror = () => {
                alert('Error reading file');
            };
            reader.readAsText(file);
        });

        // Zoom controls
        let scale = 1;
        
        document.getElementById('btn-zoom-in').onclick = () => { 
            scale = Math.min(3, scale + 0.15); 
            paper.scale(scale, scale);
        };
        
        document.getElementById('btn-zoom-out').onclick = () => { 
            scale = Math.max(0.1, scale - 0.15); 
            paper.scale(scale, scale);
        };
        
        document.getElementById('btn-fit').onclick = () => { 
            fitToScreen();
        };

        document.getElementById('btn-reset').onclick = () => {
            paper.translate(0, 0);
            fitToScreen();
        };

        // Panning functionality
        let panning = false;
        let panStart = {x: 0, y: 0};
        const container = document.getElementById('paper-container');
        
        paper.on('blank:pointerdown', (evt) => {
            panning = true;
            panStart = { x: evt.clientX, y: evt.clientY };
            container.classList.add('grabbing');
        });
        
        document.addEventListener('mousemove', (evt) => {
            if(!panning) return;
            const dx = evt.clientX - panStart.x;
            const dy = evt.clientY - panStart.y;
            panStart = { x: evt.clientX, y: evt.clientY };
            const current = paper.translate();
            paper.translate(current.tx + dx, current.ty + dy);
        });
        
        document.addEventListener('mouseup', () => { 
            panning = false; 
            container.classList.remove('grabbing'); 
        });

        // Mouse wheel zoom
        container.addEventListener('wheel', (evt) => {
            evt.preventDefault();
            const delta = evt.deltaY > 0 ? -0.1 : 0.1;
            scale = Math.max(0.1, Math.min(3, scale + delta));
            paper.scale(scale, scale);
        }, { passive: false });

        // Prevent text selection while dragging
        document.addEventListener('selectstart', (e) => {
            if (panning) e.preventDefault();
        });

        // Initialize
        loadDefault();
    </script>
    `;

    fs.writeFileSync(
        path.join(outputDir, 'erd.html'), 
        this.getPageLayout(ast, 'ER Diagram', content, 'erd')
    );
  }
}